insert into owner(full_name, address , phone, birthday, gender)
values('Bradley Alexander Abbe','Baltimore','23-35-2324','30-01-90','MALE'),
      ('Martin Quinn Abbett','Boston','23-45-4324','28-02-91','MALE'),
      ('Max Mendoza Alan','Brooklyn','23-42-2324','27-03-92','MALE'),
      ('Stephen Allen Alden','Charlotte','23-35-1324','26-04-93','MALE'),
      ('Dominic Clarke Beaner','Central Jersey','13-45-2324','25-05-94','MALE'),
      ('Theobold Elliott Bear','Philadelphia','23-45-2324','24-06-95','MALE'),
      ('Davy Mills Bearfield','Pittsburgh','22-45-2324','23-07-96','MALE'),
      ('Dominic Bowman Beatley','Queens','23-25-2324','22-08-97','MALE'),
      ('Zachary Mason Beaver','South Florida','23-42-2321','21-09-98','MALE'),
      ('Keith Oliver Chace','South Jersey','23-45-1324','20-10-99','MALE'),
      ('Manfred Webb Chadburn','Austin','23-45-2224','19-11-91','MALE'),
      ('Milton Daniels Chaddick','Chicago','23-45-2314','18-12-92','MALE'),
      ('Robin Greenwood Chadwell','Dallas','23-45-2322','17-01-93','MALE'),
      ('Justin Rodriquez Chaffey','Denver','23-45-2354','16-02-94','MALE'),
      ('Ford Simonds Chalkley','Detroit','23-45-2524','15-03-95','MALE'),
      ('Ferris Eland Chamberlain','Houston','23-45-4124','14-04-96','MALE'),
      ('Rocky Black Dabler','Santa Barbara','23-46-2324','13-05-97','MALE');


insert into services(name,price,description)
values('Pet Wellness Exams','10.1','Pet Wellness Exams are a key component of your pet’s preventative care plan and long-term health and happiness. An annual wellness visit is a checkup for your pet that includes a nose-to-tail physical examination and a discussion of your pet’s lifestyle and home environment. Your veterinarian will also ask questions about your pet’s nutrition and behavior and address any concerns that you may have. Your veterinarian may recommend additional diagnostic testing and vaccinations (for an additional cost).'),
      ('Puppy and Kitten Wellness Exams & Vaccination','13.5','We know how exciting it is for pet parents to have a new puppy or kitten in the house and that’s why we’ve created a vet visit just for them! Our in-home Wellness Exams and Vaccinations are at the heart of a happy, healthy (and growing) pet and provide essential preventative care. We offer all the core vaccines and non-core “lifestyle” vaccines that your puppy or kitten will need during their first year of life.'),
      ('In-Home Sick Visit for Pets','45.3','When your pet isn’t feeling well or you have concerns about your pet’s health and well-being, we can provide immediate help. It’s only natural to worry when you have a sick dog or sick cat, but rest assured that our veterinary doctors will be here for you and your pet when you book an in-home sick pet exam. When you want your pet seen quickly, we offer same-day and next-day in-home visits for sick pets when available.'),
      ('Telemedicine Vet Consultation','35.9','Our convenient and easy-to-use video consultation option is another reason why BetterVet is a better way for your pet to receive veterinary care. Book a video consultation appointment whenever you have questions about your pet’s behavior or nutritional needs, or to follow up with your vet about a health concern. You can book a telemedicine vet consultation from anywhere, anytime you need to!
'),
      ('In-Home Euthanasia for Dogs and Cats','40.2','When you are ready, one of our compassionate veterinary doctors will have an open, honest, and empathetic conversation about your pet''s quality of life. We consider these discussions to be one of the most difficult and important parts of our profession. Our experienced veterinary care teams can help you navigate end-of-life options for your pet.'),
      ('Quality-of-Life Consultation & Care','10.0','Compassionate In-Home Hospice Care For Your Aging & Ill Pets'),
      ('Pet Nutritional Planning','12.0','Keeping your pet at an optimal weight can help them live a long, healthy life. Good nutrition and the maintenance of a healthy weight can lower your pet’s risk of high blood pressure, diabetes, respiratory issues, and more. Whether you have a puppy or kitten, an adult, or a senior pet, nutrition is an important component of their overall wellness and preventative care plan and Pet Nutritional Planning with one of our mobile veterinarians is a great place to start.

'),
      ('Pet Behavior Counseling','11.0','Our doctors take an integrated approach to your pet’s well-being. This includes offering individual guidance specific to your pet’s age, breed, and behavior. During a home wellness visit, we will address any general behavior questions or concerns that you have. Common pet behavior issues include separation anxiety and health issues related to environmental stress.'),
      ('Dog and Cat Vaccination','14.0','Dog and cat vaccines go hand in hand with providing essential, preventative care for your pet’s long-term health and happiness. We offer all common ‘core’ vaccines and non-core vaccines for your pet in the comfort of your home. A typical vaccination schedule for a puppy or kitten starts between 6 to 8 weeks old of age and continues until they are approximately 16 weeks old. After a puppy or kitten reaches maturity, vaccines are boosted after 1 year, then booster vaccines can range from every 1-3 years depending on lifestyle.'),
      ('Domestic Pet Travel Health Certificates','15.0','When traveling with your pet within the US, there may be certain pet health requirements specific to the state(s) that you will be visiting. Certain states may require an examination by a USDA-certified veterinarian, up-to-date vaccinations, lab testing, and the issuance of an endorsed domestic pet health travel certificate for pets traveling, also called a Certificate of Veterinary Inspection. BetterVet veterinarians are USDA-certified and equipped to provide health certificates for pet travel.'),
      ('Pet Health Certificate for International Travel','10.0','International travel with your pet will require an exam by a USDA-certified veterinarian, as well as other specific qualifications, depending on the importing country where you are going, and the issuance of a vet-endorsed health certificate. Our mobile veterinarians are USDA-certified, have the authority to issue a USDA-certified pet travel certificate, and are here to help! Let BetterVet help make it easier for you to obtain an international pet travel certificate, as we can come to you.');


insert into vet(full_name, address , phone, birthday, gender,qualification)
values('Russ Abbot','Baltimore','73-35-2324','30-01-90','MALE','first'),
      ('Michael Aldridge','Boston','723-45-4324','28-02-91','MALE','first'),
      ('Chesney Allen','Brooklyn','723-42-2324','27-03-92','MALE','first'),
      ('Arthur Askey','Charlotte','723-35-1324','26-04-93','MALE','first'),
      ('Robin Askwith','Central Jersey','713-45-2324','25-05-94','MALE','second'),
      ('Rowan Atkinson','Philadelphia','723-45-2324','24-06-95','MALE','second'),
      ('Richard Ayoade','Pittsburgh','722-45-2324','23-07-96','MALE','second'),
      ('Trevor Bannister','Queens','723-25-2324','22-08-97','MALE','second'),
      ('Ronnie Barker','South Florida','723-42-2321','21-09-98','MALE','second'),
      ('Sacha Baron Cohen','South Jersey','723-45-1324','20-10-99','MALE','second'),
      ('Chris Barrie','Austin','723-45-2224','19-11-91','MALE','third'),
      ('Alfie Bass','Chicago','723-45-2314','18-12-92','MALE','third'),
      ('Colin Bean','Dallas','723-45-2322','17-01-93','MALE','third'),
      ('James Beck','Denver','723-45-2354','16-02-94','MALE','third'),
      ('Richard Beckinsale','Detroit','723-45-2524','15-03-95','MALE','third'),
      ('Harold Bennett','Houston','723-45-4124','14-04-96','MALE','third'),
      ('Michael Bentine','Santa Barbara','723-46-2324','13-05-97','MALE','third');


insert into pet(kind, name ,age, id_owner, gender)
values('CAT','Oliver','1','1','MALE'),
      ('CAT','Leo','2','2','MALE'),
      ('CAT','Milo','3','3','MALE'),
      ('CAT','Charlie','4','4','MALE'),
      ('CAT','Max','5','5','MALE'),
      ('CAT','Simba','6','6','MALE'),
      ('CAT','Luna','7','7','FEMALE'),
      ('CAT','Bella','8','8','FEMALE'),
      ('CAT','Lily','9','9','FEMALE'),
      ('CAT','Lucy','1','10','FEMALE'),
      ('DOG','Max','2','11','MALE'),
      ('DOG','Charlie','3','12','MALE'),
      ('DOG','Cooper','4','13','MALE'),
      ('DOG',' Milo','5','14','MALE'),
      ('DOG','Buddy','6','15','MALE'),
      ('DOG','Bella','7','16','FEMALE'),
      ('DOG','Lucy','8','17','FEMALE'),
      ('DOG','Daisy','9','1','FEMALE'),
      ('DOG','Molly','1','2','FEMALE'),
      ('DOG','Maggie','2','3','FEMALE'),
      ('DOG','Lola','3','4','FEMALE');

insert into pet_services(id_pet, id_services) values(1,1),
                                                    (2,1),
                                                    (3,2),
                                                    (4,2),
                                                    (5,3),
                                                    (6,3),
                                                    (7,4),
                                                    (8,4),
                                                    (9,5),
                                                    (10,5),
                                                    (11,6),
                                                    (12,6),
                                                    (13,7),
                                                    (14,7),
                                                    (15,8),
                                                    (16,8),
                                                    (17,9),
                                                    (18,9),
                                                    (19,10),
                                                    (20,10),
                                                    (21,11);


insert into vet_services(vet_id, services_id) values(1,1),
                                                    (2,1),
                                                    (3,2),
                                                    (4,2),
                                                    (5,3),
                                                    (6,3),
                                                    (7,4),
                                                    (8,4),
                                                    (9,5),
                                                    (10,5),
                                                    (11,6),
                                                    (12,6),
                                                    (13,7),
                                                    (14,7),
                                                    (15,8),
                                                    (16,8),
                                                    (17,9),
                                                    (1,9),
                                                    (2,10),
                                                    (3,10),
                                                    (4,11);